global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'
  slack_api_url: '${SLACK_WEBHOOK_URL}'
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

templates:
  - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'team-soccer-prediction'
  routes:
  - match:
      severity: critical
    receiver: 'pagerduty-critical'
    continue: true
  - match:
      severity: error
    receiver: 'slack-alerts'
    continue: true
  - match_re:
      service: ^(soccer-prediction-api|soccer-prediction-db)$
    receiver: 'team-soccer-prediction'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

receivers:
  - name: 'team-soccer-prediction'
    email_configs:
    - to: 'team@example.com'
      send_resolved: true
    slack_configs:
    - channel: '#soccer-prediction-alerts'
      send_resolved: true

  - name: 'slack-alerts'
    slack_configs:
    - channel: '#soccer-prediction-alerts'
      send_resolved: true
      title: '{{ template "slack.default.title" . }}'
      text: '{{ template "slack.default.text" . }}'

  - name: 'pagerduty-critical'
    pagerduty_configs:
    - service_key: '${PAGERDUTY_SERVICE_KEY}'
      send_resolved: true 