global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "127.0.0.1:9090"

  - job_name: "soccer-prediction-api"
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets:
        - "app:9091"  # Prometheus metrics exposed by the API
    
  - job_name: "node-exporter"
    static_configs:
      - targets:
        - "node-exporter:9100"  # System metrics
    
  - job_name: "cadvisor"
    static_configs:
      - targets:
        - "cadvisor:8080"  # Container metrics
    
  - job_name: "postgres-exporter"
    static_configs:
      - targets:
        - "postgres-exporter:9187"  # PostgreSQL metrics 