apiVersion: v1
kind: Service
metadata:
  name: soccer-prediction-frontend
  labels:
    app: soccer-prediction
    tier: frontend
spec:
  selector:
    app: soccer-prediction
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP 