apiVersion: apps/v1
kind: Deployment
metadata:
  name: soccer-prediction-backend
  labels:
    app: soccer-prediction
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: soccer-prediction
      tier: backend
  template:
    metadata:
      labels:
        app: soccer-prediction
        tier: backend
    spec:
      containers:
      - name: backend
        image: ${ACR_NAME}.azurecr.io/soccer-prediction-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: soccer-prediction-secrets
              key: database_url
        - name: API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: soccer-prediction-secrets
              key: api_secret_key
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: soccer-prediction-secrets
              key: jwt_secret_key
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: soccer-prediction-config
              key: environment
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15 